# Generated by Django 3.1.3 on 2020-11-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='detailed_description',
        ),
    ]
